// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH0zmUBKajxGG4JkQulQemFnCfpbiKe4s',
    appId: '1:716844431513:web:7474026e1358d6a9c06008',
    messagingSenderId: '716844431513',
    projectId: 'auth-with-firebase-89a74',
    authDomain: 'auth-with-firebase-89a74.firebaseapp.com',
    storageBucket: 'auth-with-firebase-89a74.appspot.com',
    measurementId: 'G-DYQZ6VJMJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9vDVEOighNaH9uYt_nu9IxWVtLyR8r-I',
    appId: '1:716844431513:android:c6e62420aae242b6c06008',
    messagingSenderId: '716844431513',
    projectId: 'auth-with-firebase-89a74',
    storageBucket: 'auth-with-firebase-89a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4A2_HlNKgS09RU61atxNFCiVYNfLAhkE',
    appId: '1:716844431513:ios:3de4ad13e7a8018dc06008',
    messagingSenderId: '716844431513',
    projectId: 'auth-with-firebase-89a74',
    storageBucket: 'auth-with-firebase-89a74.appspot.com',
    iosBundleId: 'com.example.authWithFirebaseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4A2_HlNKgS09RU61atxNFCiVYNfLAhkE',
    appId: '1:716844431513:ios:3de4ad13e7a8018dc06008',
    messagingSenderId: '716844431513',
    projectId: 'auth-with-firebase-89a74',
    storageBucket: 'auth-with-firebase-89a74.appspot.com',
    iosBundleId: 'com.example.authWithFirebaseApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH0zmUBKajxGG4JkQulQemFnCfpbiKe4s',
    appId: '1:716844431513:web:364de3cdbd543e01c06008',
    messagingSenderId: '716844431513',
    projectId: 'auth-with-firebase-89a74',
    authDomain: 'auth-with-firebase-89a74.firebaseapp.com',
    storageBucket: 'auth-with-firebase-89a74.appspot.com',
    measurementId: 'G-7VNXR614XQ',
  );
}
